//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.WCFTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFTest.IWCFTest")]
    public interface IWCFTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFTest/Test", ReplyAction="http://tempuri.org/IWCFTest/TestResponse")]
        void Test(Model.StuModel stu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFTest/TestStr", ReplyAction="http://tempuri.org/IWCFTest/TestStrResponse")]
        string TestStr(Model.StuModel stu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFTestChannel : WCFClient.WCFTest.IWCFTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFTestClient : System.ServiceModel.ClientBase<WCFClient.WCFTest.IWCFTest>, WCFClient.WCFTest.IWCFTest {
        
        public WCFTestClient() {
        }
        
        public WCFTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Test(Model.StuModel stu) {
            base.Channel.Test(stu);
        }
        
        public string TestStr(Model.StuModel stu) {
            return base.Channel.TestStr(stu);
        }
    }
}
